# fly.toml app configuration file generated for sanguine-web on 2024-03-01T20:31:59-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sanguine-web'
primary_region = 'dfw'

[build]

[[services]]
internal_port = 8_080
processes = [ "app" ]
protocol = "tcp"
script_checks = [ ]

  [services.concurrency]
  hard_limit = 100
  soft_limit = 80
  type = "requests"

  [[services.ports]]
  handlers = [ "http" ]
  port = 80
  force_https = true

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
